name: subtree

on: 
  push:
    branches: [main]

jobs:
  push:
    name: Sync git subtrees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Confiture git
        run: |
          git remote add packages-common --no-tags https://github.com/franklinkim/git-subtree-poc-common.git
      - name: Git subtree push
        run: |
          git subtree push --prefix=packages/common packages-common fork/project-b --squash --message "Merge ${{ env.GITHUB_SHA }} from ${{ env.GITHUB_REF_NAME }} ${{ env.GITHUB_REPOSITORY }} " 
