name: subtree

on: 
  push:
    branches: [main]

jobs:
  push:
    name: Push subtrees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - name: packages-common
        run: |
          git remote add packages-common --no-tags https://github.com/franklinkim/git-subtree-poc-common.git
          git subtree push --prefix=packages/common packages-common fork/project-b
